// Generated by CoffeeScript 1.3.3
(function() {
  var ModuleName, isNode, moduleName;

  isNode = typeof module !== 'undefined' && module.exports;

  if (isNode) {
    moduleName = require('../build/Release/moduleName.node');
  }

  ModuleName = function() {};

  if (isNode) {
    module.exports = ModuleName;
  }

  ModuleName.hello = function(world) {
    return moduleName.hello(world);
  };

}).call(this);
